# Generated by Django 4.1.1 on 2022-09-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upld_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
