# Generated by Django 4.1.1 on 2022-10-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_image_name_alter_image_img_alter_image_upld_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
