# Generated by Django 4.1.1 on 2022-10-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bio',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='wrk',
            field=models.TextField(default='', null=True),
        ),
    ]
