# Generated by Django 4.1.1 on 2022-10-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0012_bio_remove_about_bio_remove_about_wrk_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
