# Generated by Django 4.1.1 on 2022-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0013_delete_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='hstry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='regular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='techno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='wrk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
