# Generated by Django 4.1.1 on 2022-10-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0014_about_hstry_about_regular_about_techno_about_wrk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='personal'),
        ),
    ]
