# Generated by Django 4.1.1 on 2022-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0015_alter_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutname', models.CharField(max_length=200)),
                ('urlf', models.URLField()),
            ],
        ),
    ]
