# Generated by Django 4.1.1 on 2022-10-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0018_remove_inform_informations_inform_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inform',
        ),
    ]
