# Generated by Django 4.1.1 on 2022-10-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0019_inf_delete_inform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion_name', models.CharField(max_length=50)),
                ('passion_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
