# Generated by Django 4.1.1 on 2022-10-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0021_sing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sing',
            new_name='Singing',
        ),
    ]
